### ISSUE TITLE
Would you consider releasing tagged versions of this module?

### ISSUE THREAD

**Issue by antoninbas** [confluentinc/bincover#18]
While this is not strictly needed, it would make consuming this module easier. Consumers of the module would be able to tell which version they depend on and to determine if they need to upgrade to a more recent version. It would also enable providing guarantees about backwards-compatibility. See https://blog.golang.org/publishing-go-modules

**Comment by mpokryva** [comment]
Sure, I can do this. Let me figure out the versioning and I can do this in a few days (occupied with something else currently).

**Comment by mpokryva** [comment]
Done! Released a `v0.1.0` version. I want to leave room for possible changes in case more people start using Bincover and run into serious problems.
